from tkinter import *
root = Tk()
frame=Frame(root)
frame.pack()
bottomframe=Frame(root)
bottomframe.pack(side="bottom")
redbutton=Button(frame, text="Red", fg="red", bg="lightgreen")
redbutton.pack(side="left")
greenbutton=Button(frame, text="Brown", fg="brown", bg="yellow")
greenbutton.pack(side="left")
bluebutton=Button(frame, text="Blue", fg="blue", bg="pink")
bluebutton.pack(side="left")
blackbutton=Button(bottomframe, text="Black", fg="black", bg="white")
blackbutton.pack(side="bottom")
root.mainloop()
